version: '3.3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - /home/ubuntu/cnk_2020_docker_minecraft_server/minecraft-docker/data:/data
    environment:
      EULA: "TRUE"      
      MEMORY: 3G
    restart: always
