version: '3.3'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - /home/ubuntu/minecraft-docker/data:/data
    environment:
      EULA: "TRUE"      
    restart: always
